#!/bin/bash
uwsgi --ini master.ini --plugin python --check-static static/ -H ./.venv

# if running some python packages
#uwsgi --http :9090 --plugin python --wsgi-file server.py --callable master --master -H ./env
